# Visit our schema definition for additional information on this file format
# https://github.com/newrelic/open-install-library/blob/main/docs/recipe-spec/recipe-spec.md#schema-definition

name: rabbitmq-open-source-integration
displayName: RabbitMq Open Source Integration
description: New Relic install recipe for default RabbitMq Open Source on-host integration (via Infra-Agent)
repository: https://github.com/newrelic/nri-rabbitmq

installTargets:
  - type: host
    os: windows

keywords:
  - Integration
  - Rabbit
  - RabbitMq
  - Windows

processMatch:
  - erlsrv

validationNrql: "SELECT count(*) from RabbitmqVhostSample where hostname like '{{.HOSTNAME}}%' FACET entityGuid SINCE 10 minutes ago"

# Prompts for input from the user. These variables then become
# available to go-task in the form of {{.VAR_NAME}}
inputVars:
  - name: "NR_CLI_USERNAME"
    prompt: "RabbitMQ Username"
  - name: "NR_CLI_PASSWORD"
    prompt: "RabbitMQ Password"
  - name: "NR_CLI_PORT"
    prompt: "RabbitMQ Management Plugin Port (default: 15672)"
    default: 15672
  - name: "NR_CLI_HOSTNAME"
    prompt: "RabbitMQ Hostname (default: localhost)"
    default: "localhost"
  - name: "NR_CLI_RABBIT_CONFIG_PATH"
    prompt: "RabbitMQ Configuration File Path"
    default: /etc/rabbitmq/rabbitmq.conf
  - name: "NR_CLI_QUEUES"
    prompt: 'Queue Names to Collect (expected: ["myQueue1", "myQueue2"])'
  - name: "NR_CLI_EXCHANGES"
    prompt: 'Exchange Names to Collect (expected: ["myExchange1", "myExchange2"])'
  - name: NR_CLI_VHOSTS
    prompt: 'Vhost Names to Collect (expected: ["myVhost1", "myVhost2"]'
  - name: "NR_CLI_SSL"
    prompt: "Use SSL to connect? (true/false)"
  - name: "NR_CLI_API_CA_BUNDLE_DIR"
    prompt: "SSL Certificate Directory (if applicable)"
  - name: "NR_CLI_API_CA_BUNDLE_FILE"
    prompt: "SSL Certificate File (if applicable)"

preInstall:
  info: |2
      To capture data from the RabbitMq integration, you'll first need to meet these prerequisites:
      - RabbitMq version requirement (see https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration/#comp-req)

install:
  version: "3"
  silent: true

  tasks:
    default:
      cmds:
        - task: assert_pre_req
        - task: remove_any_previous
        - task: install

    assert_pre_req:
      cmds:
        - powershell -command '$output = Get-Service "newrelic-infra"; if ( -not ($output -like "*newrelic-infra*") ) { Write-Error "The newrelic-infra agent service is not installed on the host, but is required to install this integration. Please install the newrelic infrastructure agent." }'

    remove_any_previous:
      ignore_error: true
      cmds:
        - powershell -command '$app = Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -like "*nri-rabbitmq*"}; if ($app) { $app.Uninstall() }'
        
    install:
      label: "Installing Redis integration..."
      cmds:
        - powershell -command '(New-Object System.Net.WebClient).DownloadFile("http://download.newrelic.com/infrastructure_agent/windows/integrations/nri-rabbitmq/nri-rabbitmq-amd64.msi", "$env:TEMP\nri-rabbitmq-amd64.msi");'
        - powershell -command 'msiexec.exe /qn /i "$env:TEMP\nri-rabbitmq-amd64.msi" | Out-Null;'
        - powershell -command 'if({{.NR_CLI_SSL}} -ilike 'true')
          {
            echo "{{.SSL_CONTENT}}" >> "C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\rabbitmq-config.yml"
          }
          echo "{{.INT_CONTENT}}" >> "C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d\\rabbitmq-config.yml"
        - powershell -command 'Restart-Service newrelic-infra'
      vars:
        SSL_CONTENT: |
          integration_name: com.newrelic.rabbitmq

          instances:
            - name: rabbitmq
              command: all
              arguments:
                hostname: {{.NR_CLI_HOSTNAME}}
                port: {{.NR_CLI_PORT}}
                username: {{.NR_CLI_USERNAME}}
                password: {{.NR_CLI_PASSWORD}}
                ca_bundle_dir: {{.NR_CLI_API_CA_BUNDLE_DIR}}
                ca_bundle_file: {{.NR_CLI_API_CA_BUNDLE_FILE}}
                use_ssl: {{.NR_CLI_SSL}}
                config_path: {{.NR_CLI_RABBIT_CONFIG_PATH}}
                queues: `"{{.NR_CLI_QUEUES}}`"
                queues_regexes:
                exchanges: `"{{.NR_CLI_EXCHANGES}}`"
                exchanges_regexes:
                vhosts: `"{{.NR_CLI_VHOSTS}}`"
                vhosts_regexes:

        INT_CONTENT: |
          integration_name: com.newrelic.rabbitmq

          instances:
            - name: rabbitmq
              command: all
              arguments:
                hostname: {{.NR_CLI_HOSTNAME}}
                port: {{.NR_CLI_PORT}}
                username: {{.NR_CLI_USERNAME}}
                password: {{.NR_CLI_PASSWORD}}
                use_ssl: {{.NR_CLI_SSL}}
                config_path: {{.NR_CLI_RABBIT_CONFIG_PATH}}
                queues: `"{{.NR_CLI_QUEUES}}`"
                queues_regexes: 
                exchanges: `"{{.NR_CLI_EXCHANGES}}`"
                exchanges_regexes:
                vhosts: `"{{.NR_CLI_VHOSTS}}`"
                vhosts_regexes: 

postInstall:
  info: |2
      ⚙️  The RabbitMq configuration file can be found in /etc/newrelic-infra/integrations.d/rabbitmq-config.yml
      Edit this file to make changes or configure advanced features for this integration. See the docs for options:
      https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/rabbitmq-monitoring-integration/#config
