name: Post Run Recipe Validation Spike

on:
  workflow_dispatch:


jobs:
  validate-all:
    name: Validate All
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: 'chore/fixing-e2e-missing-curl'

      - name: Write AWS Certificate to File
        env:
          AWS_PEM: ${{ secrets.GIT_DEPLOYER_CANADA_AWS_PEM }}
        run: |
          mkdir -p configs
          rm -f configs/gitdeployerCanada.pem
          echo "$AWS_PEM" > configs/gitdeployerCanada.pem
          sudo chmod 400 configs/gitdeployerCanada.pem

      - name: Write Test Definition File JSON to file
        env:
          USER_JSON: ${{ secrets.GIT_DEPLOYER_DOCKER_USER_CONFIG }}
        run: |
          echo "$USER_JSON" > configs/gitusdkr${{ github.run_id }}.json

      - name: Pull Deployer image
        run: |
          docker pull ghcr.io/newrelic/deployer:3.3.7
          docker images ghcr.io/newrelic/deployer:3.3.7

      - name: Run deployer and cleanup
        run: |
          pwd
          cat test/manual/definitions/e2e-hacks/hack.json
          which curl
          env
          docker -D run -i\
            -v ${{ github.workspace }}/configs/:/mnt/deployer/configs/\
            -v ${{ github.workspace }}/test/:/mnt/deployer/test/\
            --entrypoint ruby ghcr.io/newrelic/deployer:3.3.7 main.rb -c configs/gitusdkr${{ github.run_id }}.json -d test/manual/definitions/e2e-hacks/hack.json -m deploy -l debug

